/**
 * Feature: jd-targeting, Property 23: JD content is never written to CloudWatch Logs
 * **Validates: Requirements 11.1, 11.2**
 *
 * For any `jdRawText` string (length 100–10000) and any runtime path through
 * `handleAnalyzeJobDescription` — success, rate-limited (pre-increment
 * fails), Bedrock-error, parse-error (non-JSON from both the initial call
 * and the stricter retry), or the rate-limit decrement path — no
 * `console.log` / `console.error` / `console.warn` / `console.info` /
 * `console.debug` invocation may have an argument that contains:
 *   (a) the raw `jdRawText`; or
 *   (b) any non-empty string field of the JD analysis response's
 *       `jdContext` (company, role, technologies[], responsibilities[],
 *       requirements[], softSkills[]).
 *
 * The privacy contract is that `logJdEvent` is the ONLY log surface for
 * JD-related events and it accepts only `{ userId, requestId, outcome,
 * jdLength, errorCode? }` — never raw JD text or `jdContext`. This property
 * test enforces that invariant at the handler level for every failure mode.
 */
import fc from 'fast-check';

// ────────────────────────────────────────────────────────────────────────────
// Module mocks (must come before the SUT import)
// ────────────────────────────────────────────────────────────────────────────

/**
 * Shared DynamoDB mock. The handler uses it for exactly two kinds of
 * `UpdateCommand` calls (increment + compensation decrement) via
 * `incrementJdRateLimit` / `decrementJdRateLimit`. Neither call carries JD
 * content, so returning `{}` or throwing a `ConditionalCheckFailedException`
 * is sufficient to drive all handler branches.
 */
const mockSend = jest.fn();

jest.mock('@aws-sdk/client-dynamodb', () => ({
  DynamoDBClient: jest.fn(() => ({})),
}));

jest.mock('@aws-sdk/lib-dynamodb', () => ({
  DynamoDBDocumentClient: {
    from: jest.fn(() => ({ send: mockSend })),
  },
  PutCommand: jest.fn((params: unknown) => ({ _type: 'PutCommand', params })),
  GetCommand: jest.fn((params: unknown) => ({ _type: 'GetCommand', params })),
  UpdateCommand: jest.fn((params: unknown) => ({ _type: 'UpdateCommand', params })),
  QueryCommand: jest.fn((params: unknown) => ({ _type: 'QueryCommand', params })),
}));

/**
 * Bedrock mock. We replace `invokeTextModelWithTimeout` so we can drive the
 * handler through every success / failure branch without going near the real
 * SDK. The wrapper pattern (`(...args) => mockInvokeTextModelWithTimeout(...)`)
 * keeps the `jest.fn` reference reassignable across test cases via
 * `mockResolvedValue` / `mockRejectedValue` / `mockResolvedValueOnce`.
 */
const mockInvokeTextModelWithTimeout = jest.fn();

jest.mock('../lambda/shared/bedrockInvoke', () => ({
  invokeTextModelWithTimeout: (...args: unknown[]) =>
    mockInvokeTextModelWithTimeout(...args),
}));

// SUT — imported AFTER the jest.mock calls so the mocks are wired up.
import { handleAnalyzeJobDescription } from '../lambda/chat/index';
import type { ChatRequest } from '../lib/types';

// ────────────────────────────────────────────────────────────────────────────
// Test fixtures
// ────────────────────────────────────────────────────────────────────────────

/**
 * Canary markers planted into the Bedrock response for the success path. They
 * use the star character `★` (U+2605) which is OUTSIDE fast-check's default
 * printable-ASCII alphabet (0x20..0x7E), so it cannot accidentally appear
 * inside a `jdRawText` string generated by `fc.string()`. Every non-empty
 * string field of `jdContext` is given a unique canary so we can assert that
 * none of them leaks into any console invocation.
 */
const JD_CONTEXT_CANARIES = {
  company: '★★CANARY_COMPANY_7f3a★★',
  role: '★★CANARY_ROLE_9b1e★★',
  technology: '★★CANARY_TECHNOLOGY_c42d★★',
  responsibility: '★★CANARY_RESPONSIBILITY_5e8a★★',
  requirement: '★★CANARY_REQUIREMENT_2a6f★★',
  softSkill: '★★CANARY_SOFTSKILL_d9c1★★',
};

const ALL_CANARY_VALUES: readonly string[] = Object.values(JD_CONTEXT_CANARIES);

/**
 * A valid JSON payload that `parseJdAnalysisResponse` + `normalizeJdContext`
 * accept without error. Shaped like the Nova Pro contract documented in
 * `buildJdAnalysisPrompt` and uses the canaries as field values.
 */
const VALID_BEDROCK_SUCCESS_RESPONSE = JSON.stringify({
  company: JD_CONTEXT_CANARIES.company,
  role: JD_CONTEXT_CANARIES.role,
  technologies: [JD_CONTEXT_CANARIES.technology],
  responsibilities: [JD_CONTEXT_CANARIES.responsibility],
  requirements: [JD_CONTEXT_CANARIES.requirement],
  softSkills: [JD_CONTEXT_CANARIES.softSkill],
  suggestedSeniority: 'senior',
  suggestedCategory: 'technical',
});

/**
 * Fixed identifiers for the user and request. Kept short and distinct from the
 * 100+ character generated `jdRawText` so there is no risk of a spurious
 * substring collision inflating the assertion.
 */
const TEST_USER_ID = 'leak-test-user-xyz';
const TEST_REQUEST_ID = 'req-leak-abc-123';

function makeConditionalCheckFailedError(): Error {
  const err = new Error('The conditional request failed');
  err.name = 'ConditionalCheckFailedException';
  return err;
}

/**
 * Serialize a single `console.*` call argument to a string so we can run a
 * substring check against it. Objects are JSON-stringified to catch cases
 * where a handler logs a full object graph that happens to contain JD
 * content. Cycles or un-stringifiable values fall back to `String(arg)`,
 * which at minimum yields `[object Object]` — still safe for `.includes`
 * checks against 100+ char JD strings.
 */
function serializeArg(arg: unknown): string {
  if (typeof arg === 'string') return arg;
  if (arg instanceof Error) {
    return `${arg.name}:${arg.message}:${arg.stack ?? ''}`;
  }
  try {
    return JSON.stringify(arg);
  } catch {
    return String(arg);
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Tests
// ────────────────────────────────────────────────────────────────────────────

describe('Property 23: JD content is never written to CloudWatch Logs', () => {
  let logSpy: jest.SpyInstance;
  let errorSpy: jest.SpyInstance;
  let warnSpy: jest.SpyInstance;
  let infoSpy: jest.SpyInstance;
  let debugSpy: jest.SpyInstance;

  beforeEach(() => {
    process.env.SESSIONS_TABLE_NAME = 'test-sessions-table';
    process.env.JD_RATE_LIMIT = '5';

    mockSend.mockReset();
    mockInvokeTextModelWithTimeout.mockReset();

    logSpy = jest.spyOn(console, 'log').mockImplementation(() => {});
    errorSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
    warnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});
    infoSpy = jest.spyOn(console, 'info').mockImplementation(() => {});
    debugSpy = jest.spyOn(console, 'debug').mockImplementation(() => {});
  });

  afterEach(() => {
    logSpy.mockRestore();
    errorSpy.mockRestore();
    warnSpy.mockRestore();
    infoSpy.mockRestore();
    debugSpy.mockRestore();
  });

  /**
   * Collect every argument from every console method invocation into a flat
   * array of strings so `.includes(jdRawText)` can be asserted uniformly.
   */
  function collectAllConsoleArgs(): string[] {
    const args: string[] = [];
    for (const spy of [logSpy, errorSpy, warnSpy, infoSpy, debugSpy]) {
      for (const call of spy.mock.calls) {
        for (const a of call) {
          args.push(serializeArg(a));
        }
      }
    }
    return args;
  }

  function clearAllConsoleSpies(): void {
    logSpy.mockClear();
    errorSpy.mockClear();
    warnSpy.mockClear();
    infoSpy.mockClear();
    debugSpy.mockClear();
  }

  function buildRequest(jdRawText: string): ChatRequest {
    return {
      action: 'analyze_job_description',
      mode: 'targeted',
      jdRawText,
    };
  }

  // ── Success path ─────────────────────────────────────────────────────────

  test('success path: neither jdRawText nor any jdContext field leaks to console', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ minLength: 100, maxLength: 500 }),
        async (jdRawText) => {
          // Reset per-iteration state. `mockReset` clears both calls and the
          // implementation, so we have to re-establish the impl each run.
          mockSend.mockReset();
          mockInvokeTextModelWithTimeout.mockReset();
          clearAllConsoleSpies();

          // Increment succeeds → handler proceeds to Bedrock; success returns
          // the canary-laced JD context with no compensation decrement.
          mockSend.mockResolvedValue({});
          mockInvokeTextModelWithTimeout.mockResolvedValue(
            VALID_BEDROCK_SUCCESS_RESPONSE,
          );

          try {
            await handleAnalyzeJobDescription(
              TEST_USER_ID,
              TEST_REQUEST_ID,
              buildRequest(jdRawText),
            );
          } catch {
            // The property is about log contents, not success/failure.
          }

          const args = collectAllConsoleArgs();
          for (const arg of args) {
            expect(arg).not.toContain(jdRawText);
            for (const canary of ALL_CANARY_VALUES) {
              expect(arg).not.toContain(canary);
            }
          }
        },
      ),
      { numRuns: 30 },
    );
  });

  // ── Rate-limited path (pre-increment fails) ──────────────────────────────

  test('rate-limited path: jdRawText does not leak to console', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ minLength: 100, maxLength: 500 }),
        async (jdRawText) => {
          mockSend.mockReset();
          mockInvokeTextModelWithTimeout.mockReset();
          clearAllConsoleSpies();

          // First (and only) send call is the rate-limit increment — we
          // reject it with a ConditionalCheckFailedException so the handler
          // short-circuits before Bedrock.
          mockSend.mockRejectedValueOnce(makeConditionalCheckFailedError());

          try {
            await handleAnalyzeJobDescription(
              TEST_USER_ID,
              TEST_REQUEST_ID,
              buildRequest(jdRawText),
            );
          } catch {
            // Handler throws RateLimitError here — expected.
          }

          // Sanity check: Bedrock must NOT have been invoked on this path.
          expect(mockInvokeTextModelWithTimeout).not.toHaveBeenCalled();

          for (const arg of collectAllConsoleArgs()) {
            expect(arg).not.toContain(jdRawText);
          }
        },
      ),
      { numRuns: 20 },
    );
  });

  // ── Bedrock-error path (increment OK → Bedrock throws → decrement OK) ───

  test('bedrock-error path: jdRawText does not leak to console (decrement path exercised)', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ minLength: 100, maxLength: 500 }),
        async (jdRawText) => {
          mockSend.mockReset();
          mockInvokeTextModelWithTimeout.mockReset();
          clearAllConsoleSpies();

          // Both send calls (increment + compensation decrement) succeed.
          mockSend.mockResolvedValue({});

          // Nova Pro fails with an error message that embeds the raw JD text
          // verbatim. `stripJdFromError` MUST redact it before any log line
          // is emitted — otherwise the assertion below will catch the leak.
          mockInvokeTextModelWithTimeout.mockRejectedValue(
            new Error(`Nova Pro invocation failed with payload: ${jdRawText}`),
          );

          try {
            await handleAnalyzeJobDescription(
              TEST_USER_ID,
              TEST_REQUEST_ID,
              buildRequest(jdRawText),
            );
          } catch {
            // Handler rethrows as JdAnalysisError — expected.
          }

          for (const arg of collectAllConsoleArgs()) {
            expect(arg).not.toContain(jdRawText);
          }
        },
      ),
      { numRuns: 20 },
    );
  });

  // ── Parse-error path (non-JSON from Bedrock twice) ───────────────────────

  test('parse-error path: jdRawText does not leak to console even when Nova Pro echoes it back as non-JSON', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ minLength: 100, maxLength: 500 }),
        async (jdRawText) => {
          mockSend.mockReset();
          mockInvokeTextModelWithTimeout.mockReset();
          clearAllConsoleSpies();

          // Both send calls succeed — we want the path where increment
          // succeeds, Bedrock returns garbage twice, and the compensation
          // decrement runs at the end.
          mockSend.mockResolvedValue({});

          // Both the initial call and the stricter retry return non-JSON
          // text that embeds the raw JD. The handler must neither log the
          // model's raw response nor the parse error itself if it contains
          // the JD.
          mockInvokeTextModelWithTimeout
            .mockResolvedValueOnce(`not json here: ${jdRawText}`)
            .mockResolvedValueOnce(`still not json: ${jdRawText}`);

          try {
            await handleAnalyzeJobDescription(
              TEST_USER_ID,
              TEST_REQUEST_ID,
              buildRequest(jdRawText),
            );
          } catch {
            // Handler rethrows as JdAnalysisError — expected.
          }

          for (const arg of collectAllConsoleArgs()) {
            expect(arg).not.toContain(jdRawText);
          }
        },
      ),
      { numRuns: 20 },
    );
  });

  // ── Decrement-path-with-downstream-failure ───────────────────────────────
  //
  // Specifically exercises the compensation decrement branch where the
  // decrement call itself fails. The outer handler swallows that failure so
  // the caller sees the original error, but we still assert no console
  // surface emits the raw JD during this cleanup.
  //
  test('rate-limit decrement failure path: jdRawText does not leak to console', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ minLength: 100, maxLength: 500 }),
        async (jdRawText) => {
          mockSend.mockReset();
          mockInvokeTextModelWithTimeout.mockReset();
          clearAllConsoleSpies();

          // First send (increment) resolves → handler calls Bedrock.
          // Second send (decrement, in the compensation branch) rejects with
          // a non-conditional error so `decrementJdRateLimit` rethrows; the
          // handler's outer try/catch swallows that failure.
          mockSend
            .mockResolvedValueOnce({})
            .mockRejectedValueOnce(new Error(`DynamoDB transient failure: ${jdRawText}`));

          mockInvokeTextModelWithTimeout.mockRejectedValue(
            new Error('Nova Pro upstream timeout'),
          );

          try {
            await handleAnalyzeJobDescription(
              TEST_USER_ID,
              TEST_REQUEST_ID,
              buildRequest(jdRawText),
            );
          } catch {
            // Handler rethrows as JdAnalysisError — expected.
          }

          for (const arg of collectAllConsoleArgs()) {
            expect(arg).not.toContain(jdRawText);
          }
        },
      ),
      { numRuns: 20 },
    );
  });
});
